### ISSUE TITLE
[Bug] Offline tests when there is a partial prefill

### ISSUE THREAD

**Issue by Shaoting-Feng** [LMCache/lmcache-tests#21]
## Describe the bug
When running offline tests, the first request has no problem. But when running the second request with the same context, I encounter the following error. I also tried the offline tests in LMCache examples. I also encounter the same error.

```shell
[rank0]: Traceback (most recent call last):
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/worker/model_runner_base.py", line 112, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 107, in new_execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 448, in forward
[rank0]:     model_output = self.model(input_ids, positions, kv_caches,
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 329, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 251, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 181, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/attention/layer.py", line 98, in forward
[rank0]:     return self.impl.forward(query,
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/attention/backends/flash_attn.py", line 743, in forward
[rank0]:     prefill_output = torch.ops.vllm.flash_attn_varlen_func(  # noqa
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/_ops.py", line 1061, in __call__
[rank0]:     return self_._op(*args, **(kwargs or {}))
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 236, in backend_impl
[rank0]:     result = self._backend_fns[device_type](*args, **kwargs)
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/attention/backends/flash_attn.py", line 49, in flash_attn_varlen_func
[rank0]:     return _flash_attn_varlen_func(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 1154, in flash_attn_varlen_func
[rank0]:     return FlashAttnVarlenFunc.apply(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 632, in forward
[rank0]:     out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
[rank0]:   File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 90, in _flash_attn_varlen_forward
[rank0]:     out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

## How to reproduce
`python3 main.py tests/tests.py -f offline_test -o outputs/`
You should monitor these files:
* /tmp/{user_name}-65431-stderr.log
* /tmp/{user_name}-65431-stdout-1.log
* /tmp/{user_name}-65431-stderr-2.log

**Comment by Shaoting-Feng** [comment]
This error no longer exists with the latest branch.
