### ISSUE TITLE
[Bug] Error in vllm_adapter when enable_chunked_prefill

### ISSUE THREAD

**Issue by Shaoting-Feng** [LMCache/lmcache-tests#22]
## Describe the error
If I enable chunked prefill without LMCache, there is no error. If I enable chunked prefill with LMCache, the error message is as follows:
```shell
Traceback (most recent call last):
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/worker/model_runner_base.py", line 112, in _wrapper
    return func(*args, **kwargs)
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 45, in new_execute_model
    model_input, is_skip = lmcache_retrieve_kv(
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_adapter.py", line 615, in lmcache_retrieve_kv
    rebuilt_model_input = build_partial_prefill_input(
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_adapter.py", line 669, in build_partial_prefill_input
    is_prefill = is_prefill_list[idx]
IndexError: list index out of range
```

## How to reproduce
`python3 main.py tests/tests.py -f test_chunk_prefill -o outputs/`

**Comment by Shaoting-Feng** [comment]
I have pulled the latest LMCache and lmcache-vllm. The error message is different now. 8K workload is fine but 16K and 24K gives the following error.
## Error message:
```shell
Traceback (most recent call last):
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/worker/model_runner_base.py", line 112, in _wrapper
    return func(*args, **kwargs)
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 173, in new_execute_model
    output: SamplerOutput = self.model.sample(
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 466, in sample
    next_tokens = self.sampler(logits, sampling_metadata)
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 249, in forward
    logits = _apply_min_tokens_penalty(logits, sampling_metadata)
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 391, in _apply_min_tokens_penalty
    assert logits_applied == logits.shape[0]
AssertionError
```
## How to reproduce

1. In lmcache-tests repo, `git checkout vary-length`
2. In lmcache-tests repo, run `python3 main.py tests/tests.py -f test_chunk_prefill -o outputs/`
3. With workload context = 16K / 24K, check the stderr log
