### ISSUE TITLE
[Bug] Different error message when prefix caching with chunk prefill

### ISSUE THREAD

**Issue by Shaoting-Feng** [LMCache/lmcache-tests#23]
## Describe the bug
If I enable chunked prefill, the error message is as https://github.com/LMCache/lmcache-tests/issues/22.
If I enable chunked prefill and prefix caching, the error message is different. This happens with 16K shared context workload.
```shell
Traceback (most recent call last):
  File "/local/shaotingf/anaconda3/envs/lmcache1/lib/python3.10/site-packages/vllm/worker/model_runner_base.py", line 112, in _wrapper
    return func(*args, **kwargs)
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 122, in new_execute_model
    store_status = lmcache_should_store(model_input, kv_caches)
  File "/local/shaotingf/lmcache1/lmcache-vllm/lmcache_vllm/vllm_adapter.py", line 338, in lmcache_should_store
    if seq_data.get_len()-1 != selected_token_indices[idx]:
IndexError: index 1 is out of bounds for dimension 0 with size 1
```
## How to reproduce
`python3 main.py tests/tests.py -f test_chunk_and_prefix -o outputs/`

**Comment by Shaoting-Feng** [comment]
Context Length of 8K does not have this error.
Context Length of 16K and 24K have this error.

I am on the latest branch of LMCache and lmcache-vllm.
